version: '3'

volumes:
  postgres_data_dev:
    driver: local
  postgres_backup_dev:
    driver: local

services:
  postgres:
    build: ./docker/postgres
    restart: always
    env_file: ./docker/envioments/.env
    ports:
      - "5100:5432"
    hostname: postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    restart: always
    env_file: ./docker/envioments/.env
    ports:
      - "8000:8000"
    hostname: django
    depends_on:
      - postgres
    volumes:
      - ./infogob/:/src
    command: sh start.sh

#  react:
#    build:
#      context: .
#      dockerfile: ./docker/react/Dockerfile
#    restart: always
#    env_file: ./docker/envioments/.env
#    ports:
#      - "3000:3000"
#    hostname: react
#    depends_on:
#      - django
#    volumes:
#      - ./frontend:/app
    #command: npm start
