# Generated by Django 2.1.10 on 2019-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ('description',),
            },
        ),
    ]
